site_name: EasyReading API Docs
site_favicon: img/favicon.ico

repo_url: 'https://github.com/whu2017/easyreading'
repo_name: 'EasyReading'

docs_dir: 'docs'
theme_dir: 'theme'

markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - footnotes
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

extra:
  palette:
    primary: 'blue grey'
    accent: 'light blue'
  font: false

pages:
  - '概述': 'index.md'
  - '用户 API': 'user.md'
  - '权限 API': 'permission.md'
  - '充值 API': 'deposit.md'
  - '站内消息 API': 'notify.md'
  - '签到 API': 'check.md'
  - '书城 API': 'bookshopping.md'
  - '个人中心 API': 'personal.md'
  - '书架 API': 'bookshelf.md'
  - '阅读 API': 'reading.md'